### ISSUE TITLE
Massive Spam in Console since today[BUG] 

### ISSUE THREAD

**Issue by CloudeLecaw** [PluginBugs/Issues-RPGBank#11]
**Describe the bug**
We dont know what produces is so here is the logpart of the console
```
[19:41:12] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.Inventory.getItem(int)" because "<local4>" is null
[19:41:12] [Server thread/WARN]: 	at RPGBank_1.0.15.jar//dev.lone.RPGBank.b.e(SourceFile:476)
[19:41:12] [Server thread/WARN]: 	at RPGBank_1.0.15.jar//dev.lone.RPGBank.b.a(SourceFile:344)
[19:41:12] [Server thread/WARN]: 	at RPGBank_1.0.15.jar//dev.lone.RPGBank.a.a(SourceFile:42)
[19:41:12] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1357.execute(Unknown Source)
[19:41:12] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[19:41:12] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[19:41:12] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:41:12] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
[19:41:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1534)
[19:41:12] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.handleContainerClose(PlayerConnection.java:3070)
[19:41:12] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3063)
[19:41:12] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:15)
[19:41:12] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:10)
[19:41:12] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[19:41:12] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:41:12] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[19:41:12] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[19:41:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[19:41:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[19:41:12] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[19:41:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[19:41:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[19:41:12] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[19:41:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1289)
[19:41:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1177)
[19:41:12] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[19:41:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[19:41:12] [Server thread/ERROR]: [31m[Minecraft] Could not pass event InventoryCloseEvent to RPGBank v1.0.15[0m
java.lang.NullPointerException: Cannot invoke "dev.lone.RPGBank.b.b.i()" because "<local3>" is null
	at dev.lone.RPGBank.b.e(SourceFile:483) ~[RPGBank_1.0.15.jar:?]
	at dev.lone.RPGBank.b.a(SourceFile:344) ~[RPGBank_1.0.15.jar:?]
	at dev.lone.RPGBank.a.a(SourceFile:42) ~[RPGBank_1.0.15.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1357.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-243]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1534) ~[paper-1.19.2.jar:git-Paper-243]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3070) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3063) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.a(ServerboundContainerClosePacket.java:10) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-243]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-243]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-243]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-243]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-243]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-243]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-243]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-243]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
This one frequently spams as more player play on the server

**Info (please complete the following information):**
![Snag_bcaa495](https://user-images.githubusercontent.com/12080017/198896434-2fd50e79-4129-4f30-8ef4-d03aa0a1fe5a.png)

**Comment by CloudeLecaw** [comment]
it didnt appeared aggain. so i will close the ticket for now and may reopen it if i see something aggain that might helps to see what was the cause of it.
