### ISSUE TITLE
[BUG] PlaceholderApi Hook Error

### ISSUE THREAD

**Issue by SirCraftypants** [PluginBugs/Issues-RPGBank#13]
**Describe the bug**
[04:55:58 ERROR]: [RPGBank] Failed to hook PlaceholderAPI! Make sure you have the latest version and it's not a corrupted JAR.
[04:55:58 WARN]: java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract java.lang.String getIdentifier()' of abstract class me.clip.placeholderapi.expansion.PlaceholderExpansion.
[04:55:58 WARN]:        at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:214)
[04:55:58 WARN]:        at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.expansion.PlaceholderExpansion.register(PlaceholderExpansion.java:139)
[04:55:58 WARN]:        at RPGBank_1.0.16.jar//dev.lone.RPGBank.c.a.e(SourceFile:7)
[04:55:58 WARN]:        at RPGBank_1.0.16.jar//dev.lone.RPGBank.Main.onEnable(SourceFile:83)
[04:55:58 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[04:55:58 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[04:55:58 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[04:55:58 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
[04:55:58 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
[04:55:58 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[04:55:58 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
[04:55:58 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[04:55:58 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1100)
[04:55:58 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[04:55:58 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
**To Reproduce**
Installed latest RPGBank and PlaceholderApi and run the server

**Expected behavior**
The Above Error

**Screenshots**
None

**Info (please complete the following information):**
 - Server version: (Paper 1.19.2)
 - Client version: (Minecraft 1.19.2)
 - Plugin version: (1.0.16)

**Additional context**
There is nothing wrong with the placeholderapi jar or the rpgbank jar, both have been downloaded and installed multiple times using multiple browsers, sftp and server panel.

**Comment by SirCraftypants** [comment]
I've tried both PlaceholderAPI 2.11.2 and PlaceholderAPI 2.11.3 Dev 160

Both throw the same error shown above.

**Comment by LoneDev6** [comment]
Seems github didn't send my message.
Thanks for the report, this issue will be looked in the next hours, I'm sure it's caused by a linkage error of the library for some reason, error caused on my end.

**Comment by LoneDev6** [comment]
Fixed, thanks
