### ISSUE TITLE
would be nice to have support for 1.20.2

### ISSUE THREAD

**Issue by CloudeLecaw** [PluginBugs/Issues-RPGBank#17]
```
[08:54:08] [Server thread/INFO]: [RPGBank] [0;32;1mDetected Vault![m
[08:54:08] [Server thread/WARN]: [RPGBank] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.3-b131 which is not a depend or softdepend of this plugin.
[08:54:08] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: rpgbank [1.0.0]
[08:54:10] [Server thread/ERROR]: Error occurred while enabling RPGBank v1.0.16-r3 (Is it up to date?)
dev.lone.LoneLibs.nbt.nbtapi.NbtApiException: [?]Error while calling the method 'putBoolean(java.lang.String,boolean)', loaded: true, Enum: COMPOUND_SET_BOOLEAN, Passed Class: class java.lang.Boolean
	at dev.lone.LoneLibs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:358) ~[?:?]
	at dev.lone.LoneLibs.nbt.nbtapi.NBTReflectionUtil.setData(NBTReflectionUtil.java:615) ~[?:?]
	at dev.lone.LoneLibs.nbt.nbtapi.NBTCompound.setBoolean(NBTCompound.java:416) ~[?:?]
	at dev.lone.RPGBank.b.a(SourceFile:763) ~[?:?]
	at dev.lone.RPGBank.b.b(SourceFile:793) ~[?:?]
	at dev.lone.RPGBank.b.<init>(SourceFile:73) ~[?:?]
	at dev.lone.RPGBank.Main.a(SourceFile:130) ~[?:?]
	at dev.lone.RPGBank.Main.onEnable(SourceFile:105) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:548) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:462) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:577) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:400) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3881-Spigot-17ca32d-f71a799]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:202) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:100) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at dev.lone.LoneLibs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:355) ~[?:?]
	... 18 more
```

i aspect it needs an update of lonedev libs

**Comment by CloudeLecaw** [comment]
well we are using the LoneDev 1.0.26

Would be nice to have a statement if the RPG-banker are working now with this, or with the plugin itself might needs a little update... :)

**Comment by LoneDev6** [comment]
Update LoneLibs, I fixed the issue, thanks!
