### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Zeronic76** [PluginBugs/Issues-RPGBank#2]
**Info (please complete the following information):**
 - Server version: (paper 1.17)
 - Client version: (vanillla)
 - Plugin version: ("latest")

**Additional context**

[00:51:19 ERROR]: Error occurred while enabling RPGBank v1.0.14 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getItemMeta()" because "<local1>" is null
        at dev.lone.RPGBank.b.a(SourceFile:668) ~[?:?]
        at dev.lone.RPGBank.b.b(SourceFile:708) ~[?:?]
        at dev.lone.RPGBank.b.<init>(SourceFile:63) ~[?:?]
        at dev.lone.RPGBank.Main.f(SourceFile:116) ~[?:?]
        at dev.lone.RPGBank.Main.onEnable(SourceFile:91) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-79]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-79]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-79]
        at net.Lenni0451.SpigotPluginManager.utils.PluginUtils.enablePlugin(PluginUtils.java:94) ~[?:?]
        at net.Lenni0451.SpigotPluginManager.utils.PluginUtils.loadPlugin(PluginUtils.java:212) ~[?:?]
        at net.Lenni0451.SpigotPluginManager.utils.PluginUtils.loadPlugin(PluginUtils.java:172) ~[?:?]
        at net.Lenni0451.SpigotPluginManager.commands.subs.Reload_Sub.execute(Reload_Sub.java:36) ~[?:?]
        at net.Lenni0451.SpigotPluginManager.commands.PluginManager_Command.lambda$onCommand$0(PluginManager_Command.java:89) ~[?:?]
        at net.Lenni0451.SpigotPluginManager.commands.PluginManager_Command.onCommand(PluginManager_Command.java:104) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.jar:git-Paper-79]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.jar:git-Paper-79]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.jar:git-Paper-79]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:784) ~[patched_1.17.jar:git-Paper-79]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:516) ~[patched_1.17.jar:git-Paper-79]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:478) ~[patched_1.17.jar:git-Paper-79]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-79]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-79]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-79]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[00:51:19 INFO]: [RPGBank] Disabling RPGBank v1.0.14

**Comment by LoneDev6** [comment]
Probably something is misconfigured, I have to check your config.yml file.
