### ISSUE TITLE
please add support for 1.21 server

### ISSUE THREAD

**Issue by CloudeLecaw** [PluginBugs/Issues-RPGBank#20]
Currently the plugin throws errors on loading

```
[19:37:08] [Server thread/INFO]: [RPGBank] Enabling RPGBank v1.0.16-r3
[19:37:08] [Server thread/INFO]: [m
[19:37:08] [Server thread/INFO]: [0;33;1m-[0;33;22m=[0;30;1m[[0;32;1m[21m RPGBank [0;30;1m][0;33;22m=[0;33;1m-[m
[19:37:08] [Server thread/INFO]: [m
[19:37:08] [Server thread/INFO]: [0;33;22mVersion: [0;36;1m1.0.16-r3[m
[19:37:08] [Server thread/INFO]: [0;33;22mServer version: [0;36;1m4223-Spigot-146439e-d01c70e (MC: 1.21)[m
[19:37:08] [Server thread/INFO]: [m
[19:37:08] [Server thread/INFO]: [m
[19:37:08] [Server thread/INFO]: [RPGBank] [0;32;1mDetected Vault![m
[19:37:08] [Server thread/WARN]: [RPGBank] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.3-b131 which is not a depend or softdepend of this plugin.
[19:37:08] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: rpgbank [1.0.0]
[19:37:08] [Server thread/ERROR]: Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_21_R1.inventory.SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_21_R1.inventory.SerializableMeta for deserialization
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "org.bukkit.craftbukkit.v1_21_R1.inventory.SerializableMeta.getObject(java.lang.Class, java.util.Map, Object, boolean)" is null
	at org.bukkit.craftbukkit.v1_21_R1.inventory.CraftMetaBookSigned.<init>(CraftMetaBookSigned.java:119) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at org.bukkit.craftbukkit.v1_21_R1.inventory.SerializableMeta.deserialize(SerializableMeta.java:75) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:87) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:129) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:209) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:58) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:576) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:210) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:552) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:597) ~[snakeyaml-2.2.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:49) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]
	at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:37) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:162) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:160) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:160) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:119) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:308) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at dev.lone.RPGBank.b.b.b(SourceFile:37) ~[?:?]
	at dev.lone.RPGBank.b.b.<init>(SourceFile:32) ~[?:?]
	at dev.lone.RPGBank.b.<init>(SourceFile:61) ~[?:?]
	at dev.lone.RPGBank.Main.a(SourceFile:130) ~[?:?]
	at dev.lone.RPGBank.Main.onEnable(SourceFile:105) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:567) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:481) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
[19:37:08] [Server thread/ERROR]: Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_21_R1.inventory.SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_21_R1.inventory.SerializableMeta for deserialization
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.bukkit.craftbukkit.v1_21_R1.inventory.SerializableMeta.getObject(java.lang.Class, java.util.Map, Object, boolean)" is null
	at org.bukkit.craftbukkit.v1_21_R1.inventory.CraftMetaBookSigned.<init>(CraftMetaBookSigned.java:120) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at org.bukkit.craftbukkit.v1_21_R1.inventory.SerializableMeta.deserialize(SerializableMeta.java:75) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:87) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:129) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:209) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:58) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:576) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:210) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:552) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:597) ~[snakeyaml-2.2.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:49) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]
	at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:37) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:162) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:160) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:160) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:119) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:308) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at dev.lone.RPGBank.b.b.b(SourceFile:37) ~[?:?]
	at dev.lone.RPGBank.b.b.<init>(SourceFile:32) ~[?:?]
	at dev.lone.RPGBank.b.<init>(SourceFile:61) ~[?:?]
	at dev.lone.RPGBank.Main.a(SourceFile:130) ~[?:?]
	at dev.lone.RPGBank.Main.onEnable(SourceFile:105) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:567) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:481) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
[19:37:08] [Server thread/ERROR]: Error occurred while enabling RPGBank v1.0.16-r3 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class dev.lone.LoneLibs.nbt.nbtapi.NBTReflectionUtil
	at dev.lone.LoneLibs.nbt.nbtapi.NBTCompound.setBoolean(NBTCompound.java:512) ~[?:?]
	at dev.lone.RPGBank.b.a(SourceFile:763) ~[?:?]
	at dev.lone.RPGBank.b.b(SourceFile:793) ~[?:?]
	at dev.lone.RPGBank.b.<init>(SourceFile:73) ~[?:?]
	at dev.lone.RPGBank.Main.a(SourceFile:130) ~[?:?]
	at dev.lone.RPGBank.Main.onEnable(SourceFile:105) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:567) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:481) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4223-Spigot-146439e-d01c70e]
	at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Server thread"]
	at java.base/java.util.Objects.requireNonNull(Objects.java:220) ~[?:?]
	at java.base/java.lang.Class.getDeclaredField(Class.java:2784) ~[?:?]
	at dev.lone.LoneLibs.nbt.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:59) ~[?:?]
	at dev.lone.LoneLibs.nbt.nbtapi.NBTCompound.getType(NBTCompound.java:1348) ~[?:?]
	at dev.lone.LoneLibs.nbt.nbtapi.NBTCompound.addCompound(NBTCompound.java:765) ~[?:?]
	at dev.lone.LoneLibs.nbt.nbtapi.NBTCompound.getOrCreateCompound(NBTCompound.java:805) ~[?:?]
	at de.erethon.headlib.Generic.createOwnerCompound(Generic.java:64) ~[?:?]
	at de.erethon.headlib.HeadLib.setSkullOwner(HeadLib.java:411) ~[?:?]
	at de.erethon.headlib.HeadLib.setSkullOwner(HeadLib.java:407) ~[?:?]
	at dev.lone.EpicBackpacks.a.a(SourceFile:247) ~[?:?]
	at dev.lone.EpicBackpacks.h.d(SourceFile:202) ~[?:?]
	at dev.lone.EpicBackpacks.Main.d(SourceFile:178) ~[?:?]
	at dev.lone.EpicBackpacks.Main.g(SourceFile:166) ~[?:?]
	at dev.lone.EpicBackpacks.Main.onEnable(SourceFile:117) ~[?:?]
	... 11 more
```

**Comment by CloudeLecaw** [comment]
currently we get this error on 1.21

The Bank opens and closes but this error arrpears in console

```
[01:04:46] [Server thread/INFO]: Cloude_Lecaw issued server command: /rpgbbanker open
[01:04:49] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.Inventory.getItem(int)" because "<local4>" is null
[01:04:49] [Server thread/WARN]: 	at dev.lone.RPGBank.b.e(SourceFile:516)
[01:04:49] [Server thread/WARN]: 	at dev.lone.RPGBank.b.a(SourceFile:384)
[01:04:49] [Server thread/WARN]: 	at dev.lone.RPGBank.a.a(SourceFile:38)
[01:04:49] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[01:04:49] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[01:04:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[01:04:49] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:04:49] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601)
[01:04:49] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588)
[01:04:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_21_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1437)
[01:04:49] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2527)
[01:04:49] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInCloseWindow.a(SourceFile:32)
[01:04:49] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInCloseWindow.a(SourceFile:8)
[01:04:49] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:35)
[01:04:49] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(SourceFile:18)
[01:04:49] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162)
[01:04:49] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[01:04:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1270)
[01:04:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:203)
[01:04:49] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:136)
[01:04:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1249)
[01:04:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1242)
[01:04:49] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.bB(SourceFile:121)
[01:04:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1213)
[01:04:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1078)
[01:04:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[01:04:49] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
[01:04:49] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to RPGBank v1.0.16-r3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_21_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1437) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2527) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.network.protocol.game.PacketPlayInCloseWindow.a(SourceFile:32) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.network.protocol.game.PacketPlayInCloseWindow.a(SourceFile:8) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:35) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1270) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:203) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:136) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1249) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1242) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.util.thread.IAsyncTaskHandler.bB(SourceFile:121) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1213) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1078) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "dev.lone.RPGBank.b.b.d()" because "<local3>" is null
	at dev.lone.RPGBank.b.e(SourceFile:523) ~[?:?]
	at dev.lone.RPGBank.b.a(SourceFile:384) ~[?:?]
	at dev.lone.RPGBank.a.a(SourceFile:38) ~[?:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	... 21 more
```

**Comment by CloudeLecaw** [comment]
well 3 weeks has passt. i know your busy. but would still be nice to see RPGBank on Spigot 1.21 its one of the last two plugins we wanne see back :3

**Comment by CloudeLecaw** [comment]
1.21.1 is allrady on the server and we wait for a omepack of the RPG-Bank and EpicBacks from you <3

**Comment by Futodama** [comment]
As well as the author of the post, I expect support for 1.21.1-1.21.2 versions.
