### ISSUE TITLE
Exception in remapping 1.21.1 and newer. | Support versions 1.21+

### ISSUE THREAD

**Issue by Futodama** [PluginBugs/Issues-RPGBank#22]
**Describe the bug**
Greetings, my dear developer. I am updating my server to the newest versions 1.21 and I am faced with the fact that my most favorite plugin among my players cannot work on new versions. Please fix this annoying error and make support for this version.

**To Reproduce**
1. 'Run the server on the core of Purpur version 1.21.1.'
2. See error on startup

**ERROR IN CONSOLE**

[23:48:16 ERROR]: [PluginRemapper] Encountered exception remapping plugins
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to remap plugin jar 'plugins\RPGBank_1.0.16-r3.jar'
        at java.base/java.util.concurrent.CompletableFuture.wrapInCompletionException(CompletableFuture.java:323) ~[?:?]        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:359) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:364) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:693) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:526) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
Caused by: java.lang.RuntimeException: Failed to remap plugin jar 'plugins\RPGBank_1.0.16-r3.jar'
        at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:358) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:690) ~[?:?]
        ... 4 more
Caused by: java.lang.RuntimeException: Failed to execute task dev/lone/RPGBank/b
        at net.neoforged.art.internal.AsyncHelper.invokeAll(AsyncHelper.java:56) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.AsyncHelper.consumeAll(AsyncHelper.java:36) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:177) ~[purpur-1.21.1.jar:?]
        at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:95) ~[purpur-1.21.1.jar:?]
        at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:355) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:690) ~[?:?]
        ... 4 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Duplicate key a (attempted merging values default dev/lone/RPGBank/b/a Ldev/lone/RPGBank/a; and default dev/lone/RPGBank/b/a Ljava/util/Map;)
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
        at net.neoforged.art.internal.AsyncHelper.invokeAll(AsyncHelper.java:52) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.AsyncHelper.consumeAll(AsyncHelper.java:36) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:177) ~[purpur-1.21.1.jar:?]
        at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:95) ~[purpur-1.21.1.jar:?]
        at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:355) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:690) ~[?:?]
        ... 4 more
Caused by: java.lang.IllegalStateException: Duplicate key a (attempted merging values default dev/lone/RPGBank/b/a Ldev/lone/RPGBank/a; and default dev/lone/RPGBank/b/a Ljava/util/Map;)
        at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135) ~[?:?]
        at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182) ~[?:?]
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215) ~[?:?]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560) ~[?:?]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:727) ~[?:?]
        at net.neoforged.art.internal.ClassProviderImpl$ClassInfo.<init>(ClassProviderImpl.java:122) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.ClassProviderBuilderImpl.lambda$addClass$1(ClassProviderBuilderImpl.java:64) ~[AutoRenamingTool-2.0.3.jar:?]
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1713) ~[?:?]
        at net.neoforged.art.internal.ClassProviderBuilderImpl.addClass(ClassProviderBuilderImpl.java:64) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.RenamerImpl.lambda$run$2(RenamerImpl.java:178) ~[purpur-1.21.1.jar:?]
        at net.neoforged.art.internal.AsyncHelper.lambda$null$0(AsyncHelper.java:33) ~[AutoRenamingTool-2.0.3.jar:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        ... 3 more

**Info (please complete the following information):**
 - Server version: Purpur Version: 1.21.1-2329-803bf62 (MC: 1.21.1)
 - Client version: 1.21.1
 - Plugin version: RPGBank_1.0.16-r3

**Comment by Futodama** [comment]
LoneLibs version 1.0.59

**Comment by Futodama** [comment]
@LoneDev6 I'm sorry to mention it. I really need this plugin. I own an RPG project where the banker is a very important part of the server economy. Please find at least some time to revive this wonderful plugin.

**Comment by Futodama** [comment]
Does it make sense to expect this plugin in the future or is it abandoned?

**Comment by LoneDev6** [comment]
I hope to find the time in the next days to update the plugin, thanks for the patience

**Comment by Futodama** [comment]
> I hope to find the time in the next days to update the plugin, thanks for the patience

Is there any progress on this issue?

**Comment by Futodama** [comment]
A new version of the game 1.21.4 was released, but the update to 1.21 as a whole has not been received. I am still hoping to update this plugin.

**Comment by NeotenySS** [comment]
LoneDev, add support please, I know mojang like to roll out updates every 2-3 months.... But still...
1.21.5 will be released in the spring, but they say it's minor changes there
https://mclo.gs/2yHNcsX

**Comment by 00Hrtz** [comment]
I hope support for 1.21.4 will be done in the next update.

**Comment by Futodama** [comment]
It is wonderful!

**Comment by Futodama** [comment]
It is wonderful!

**Comment by 00Hrtz** [comment]
From the information i have, Lonedev is prioritizing his more used plugins as he's become swamped with the amount of plugins he owns and updates on his own, he's considering making plugins like RPGBank and so on, open source so other Devs help keep them updated and working.  As it stands Itemsadder takes precedent seeing as it's his most used plugin, all others are queued and i can not say when RPGBank will be updated. There is no ETA.

I am strongly considering alternative plugins, whether that's for the short term or not i don't yet know.

All i can suggest is maybe you try alternatives, some example searches are:

`Bank Plugin`
`Money Cheque Plugin`
`Expbottle Plugin`

I found a few free ones so i'm sure you'll locate them also should you wish too.

As it stands there's no eta for Rpgbank but i'm sure it will be worked on in the future, it's too good to disappear.
