### ISSUE TITLE
1.19 has come our[BUG] 

### ISSUE THREAD

**Issue by CloudeLecaw** [PluginBugs/Issues-RPGBank#9]
May its jsut because LoneDevLib broke.
but here is what i get from console

```
[18:52:55] [Server thread/WARN]: [33m[dev.lone.RPGBank.Main] [RPGBank] Loaded class {0} from {1} which is not a depend or softdepend of this plugin.[0m
[18:52:55] [Server thread/ERROR]: [31m[Minecraft] Error occurred while enabling RPGBank v1.0.15 (Is it up to date?)[0m
dev.lone.LoneLibs.nbt.nbtapi.NbtApiException: Error while calling the method 'putBoolean(java.lang.String,boolean)', loaded: true, Enum: COMPOUND_SET_BOOLEAN Passed Class: class java.lang.Boolean
	at dev.lone.LoneLibs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:180) ~[?:?]
	at dev.lone.LoneLibs.nbt.nbtapi.NBTReflectionUtil.setData(NBTReflectionUtil.java:602) ~[?:?]
	at dev.lone.LoneLibs.nbt.nbtapi.NBTCompound.setBoolean(NBTCompound.java:385) ~[?:?]
	at dev.lone.RPGBank.b.a(SourceFile:723) ~[?:?]
	at dev.lone.RPGBank.b.b(SourceFile:753) ~[?:?]
	at dev.lone.RPGBank.b.<init>(SourceFile:67) ~[?:?]
	at dev.lone.RPGBank.Main.f(SourceFile:116) ~[?:?]
	at dev.lone.RPGBank.Main.onEnable(SourceFile:91) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:513) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:427) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:582) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:401) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:966) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3499-Spigot-87c4d13-64c1527]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at dev.lone.LoneLibs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:178) ~[?:?]
	... 18 more
```

**Comment by CloudeLecaw** [comment]
fixed in latetest release :)
